#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -rf VTK
rm -rf constant/cellToRegion constant/polyMesh/sets
rm -rf 0/electrolyte
rm -rf 0/cathode
rm -rf 0/anode
rm -rf 0/bipolar
rm -f 0/cellToRegion
rm -rf constant/electrolyte/polyMesh
rm -rf constant/cathode/polyMesh
rm -rf constant/anode/polyMesh
rm -rf constant/bipolar/polyMesh
# ----------------------------------------------------------------- end-of-file
