#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Cite as: Electrochimica Acta 290 (2018) 676-685
# https://doi.org/10.1016/j.electacta.2018.09.121

# see: https://github.com/ancolli/secondaryCurrentDistributionFoam

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication topoSet
runApplication splitMeshRegions -cellZones -overwrite

# remove fluid fields from solid regions (important for post-processing)
for i in cathode anode bipolar
do
   rm -f 0*/$i/{fi,kf}
done

for i in electrolyte cathode anode bipolar
do
   changeDictionary -region $i > log.changeDictionary.$i 2>&1
done

#-- Run on single processor
runApplication `getApplication`

multiRegionPotentialFoam -postProcess -func surfaces -latestTime


echo
echo "creating files for paraview post-processing"
echo
paraFoam -touchAll

# ----------------------------------------------------------------- end-of-file
