#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

runApplication blockMesh
runApplication topoSet
runApplication splitMeshRegions -cellZones -overwrite

#-- Run on single processor
runApplication `getApplication`

# Post-process
multiRegionPotentialFoam -postProcess -func surfaces -latestTime
paraFoam -touchAll

# ----------------------------------------------------------------- end-of-file
